yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>', views.group_posts, name='group_list'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
  LoginView, 
  LogoutView, 
  PasswordChangeView, 
  PasswordChangeDoneView,
  PasswordResetView,
  PasswordResetDoneView,
  PasswordResetConfirmView,
  PasswordResetCompleteView,
)
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path(
      'logout/',
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path(
      'signup/', 
      views.SignUp.as_view(), 
      name='signup'),
    path(
      'login/',
      LoginView.as_view(template_name='users/login.html'),
      name='login'
    ),
    path(
      'password_change/',
      PasswordChangeView.as_view(template_name='users/password_change_form.html'),
      name='password_change'
    ),
    path(
      'password_change/done/',
      PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
      name='password_change_done'
    ),
    path(
      'password_reset/',
      PasswordResetView.as_view(template_name='users/password_reset_form.html'),
      name='password_reset'
    ),
    path(
      'password_reset/done/',
      PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
      name='password_reset_done'
    ),
    path(
      'reset/<uidb64>/<token>/',
      PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
      name='password_reset_confirm'
    ),
    path(
      'reset/done/',
      PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
      name='password_reset_complete'
    ),
] 

yatube/yatube/urls.py
#from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls), 
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Адрес', primary_key=True)
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст публикации')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        #в модели User создается свойство posts, которое ссылается на все записи автора
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group_name',
        verbose_name='Сообщество',
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email') 

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render

from posts.models import Group, Post


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    posts = Post.objects.all()[:10]
    context = {
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    title = f'Записи сообщества {slug}'
    posts = group.group_name.all()[:10]
    context = {
        'group': group,
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from users.forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/base.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <title>
      {% block title %}
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<p class="border-top text-center py-3">
    © 2020 Copyright <span style="color:red">Ya</span>tube
</p> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
    </div>
  </nav>      

yatube/templates/includes/password_draw_form.html
{% load user_filters %}
{% csrf_token %}
{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/password_form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    {% for post in posts %}
      <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>    
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}  
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ title }}</h1>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
    <p>{{ post.text }}</p>
    {% if post.group%}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </div> 
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Выход</div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Войти на сайт</div>
      <div class="card-body">
        {% include 'includes/password_form_errors.html' %}
        <form method="post"
          {% if action_url %}
            action="{% url action_url %}"
          {% endif %}
        >
          {% include 'includes/password_draw_form.html' %}  
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Войти</button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Пароль изменён</div>
      <div class="card-body">
        <p>Пароль изменён успешно</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Изменить пароль</div>
      <div class="card-body">
        {% include 'includes/password_form_errors.html' %}
        <form method="post" action="{% url 'users:password_change' %}">
          {% include 'includes/password_draw_form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Изменить пароль</button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->  
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошел успешно{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Восстановление пароля завершено</div>
      <div class="card-body">
        <p>Ваш пароль был сохранен. Используйте его для входа</p>
        <a href="{% url 'users:login' %}">войти</a>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% if validlink %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Введите новый пароль</div>
        <div class="card-body">
          {% include 'includes/password_form_errors.html' %}
          <form method="post">
            {% include 'includes/password_draw_form.html' %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->  
{% else %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ошибка</div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Отправлено письмо</div>
      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо 
        со ссылкой для восстановления пароля</p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Чтобы сбросить старый пароль — введите адрес электронной почты, 
        под которым вы регистрировались
      </div>
      <div class="card-body">
        {% include 'includes/password_form_errors.html' %}
        <form method="post" action="{% url 'users:password_reset' %}">
          {% include 'includes/password_draw_form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Изменить пароль</button>
          </div>
        </form> 
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->  
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>
      <div class="card-body">
        {% include 'includes/password_form_errors.html' %}
        <form method="post" action="{% url 'users:signup' %}">
          {% include 'includes/password_draw_form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 